### ISSUE TITLE
Problem with installing mods into Modifications folder

### ISSUE THREAD

**Issue by AMGarkin** [CasDragon/ModFinder#9]
When installing mods that should be installed into Modifications folder such as [Flame Weapon Expert Fix](https://www.nexusmods.com/warhammer40kroguetrader/mods/171) or [Heavy Bolter Patterned Variants](https://www.nexusmods.com/warhammer40kroguetrader/mods/168) ModFinder extracts correctly only files in the root of the archive, but nothing what is inside of subfolders and it also ignores empty folders. In order to mod work correctly, I have to extract files manually.

Installation directory looks like this (2 files and 2 empty folders):
```
Flamer Fix 2
│   OwlcatModificationManifest.json
│   OwlcatModificationSettings.json
│
├───Blueprints
└───Bundles
```

Here is installation log when I have tried to install Flame Weapon Expert Fix:
```
[10.30 07:20:08][V] Creating mod directory. "C:\Users\Garkin\AppData\LocalLow\Owlcat Games\Warhammer 40000 Rogue Trader\Modifications"
[10.30 07:20:08][V] Finished creating mod directory. "C:\Users\Garkin\AppData\LocalLow\Owlcat Games\Warhammer 40000 Rogue Trader\Modifications\Flamer Fix 2"
[10.30 07:20:08][V] C:\Users\Garkin\AppData\LocalLow\Owlcat Games\Warhammer 40000 Rogue Trader\Modifications\Flamer Fix 2
[10.30 07:20:08][V] [Line 311] Destination is - C:\Users\Garkin\AppData\LocalLow\Owlcat Games\Warhammer 40000 Rogue Trader\Modifications\Flamer Fix 2
[10.30 07:20:08][V] System.IO.IOException: Extracting Zip entry would have resulted in a file outside the specified destination directory.
   at System.IO.Compression.ZipFileExtensions.ExtractRelativeToDirectory(ZipArchiveEntry source, String destinationDirectoryName, Boolean overwrite)
   at System.IO.Compression.ZipFileExtensions.ExtractToDirectory(ZipArchive source, String destinationDirectoryName, Boolean overwriteFiles)
   at ModFinder.Mod.ModInstaller.<>c__DisplayClass6_0.<InstallFromZip>b__2() in C:\Users\Kyle\source\repos\ModFinder\ModFinderClient\Mod\ModInstaller.cs:line 316
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at ModFinder.Mod.ModInstaller.InstallFromZip(String path, ModViewModel viewModel, Boolean isUpdate) in C:\Users\Kyle\source\repos\ModFinder\ModFinderClient\Mod\ModInstaller.cs:line 299
[10.30 07:20:08][V] Starting to extract in parts
[10.30 07:20:08][V] [Line 259] Destination is - C:\Users\Garkin\AppData\LocalLow\Owlcat Games\Warhammer 40000 Rogue Trader\Modifications\Flamer Fix 2
[10.30 07:20:08][V] [Line 260] File is - OwlcatModificationManifest.json
[10.30 07:20:08][V] [Line 262] Full path is - C:\Users\Garkin\AppData\LocalLow\Owlcat Games\Warhammer 40000 Rogue Trader\Modifications\Flamer Fix 2\OwlcatModificationManifest.json
[10.30 07:20:08][V] [Line 259] Destination is - C:\Users\Garkin\AppData\LocalLow\Owlcat Games\Warhammer 40000 Rogue Trader\Modifications\Flamer Fix 2
[10.30 07:20:08][V] [Line 260] File is - OwlcatModificationSettings.json
[10.30 07:20:08][V] [Line 262] Full path is - C:\Users\Garkin\AppData\LocalLow\Owlcat Games\Warhammer 40000 Rogue Trader\Modifications\Flamer Fix 2\OwlcatModificationSettings.json
[10.30 07:20:08][V] [Line 259] Destination is - C:\Users\Garkin\AppData\LocalLow\Owlcat Games\Warhammer 40000 Rogue Trader\Modifications\Flamer Fix 2
[10.30 07:20:08][V] [Line 260] File is - Blueprints/FlameWeaponSpecialization.jbp_patch
[10.30 07:20:08][V] [Line 262] Full path is - C:\Users\Garkin\AppData\LocalLow\Owlcat Games\Warhammer 40000 Rogue Trader\Modifications\Flamer Fix 2\Blueprints/FlameWeaponSpecialization.jbp_patch
[10.30 07:20:08][V] [Line 259] Destination is - C:\Users\Garkin\AppData\LocalLow\Owlcat Games\Warhammer 40000 Rogue Trader\Modifications\Flamer Fix 2
[10.30 07:20:08][V] [Line 260] File is - Bundles/FlamerFix2_BlueprintDirectReferences
[10.30 07:20:08][V] [Line 262] Full path is - C:\Users\Garkin\AppData\LocalLow\Owlcat Games\Warhammer 40000 Rogue Trader\Modifications\Flamer Fix 2\Bundles/FlamerFix2_BlueprintDirectReferences
[10.30 07:20:08][I] Flame Weapon Expert Fix successfully installed with version 1.0.4.
```

**Comment by CasDragon** [comment]
Ignoring empty folders isn't a bug, nor should it cause any issues. That being said, not extracting subfolders correctly is definitely a bug. Surprised no one has reported this until now. Should have a fix out tonight, I think

**Comment by CasDragon** [comment]
While I was optimistic about doing it that night, I believe I have fixed it with the newest version. 

As always, let me know if there's any issues
